version: "2.2"
services:
  
  Product:
    container_name: Product
    build: ./Product
    ports:
      - "8082:8082"
    hostname: compte
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    image: "product"
    depends_on:
      - Eureka
 
  Eureka:
    container_name: serviceregistry
    build: ./eureuka
    ports:
      - "8761:8761"
    hostname: serviceregistry
    image: "eureka"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
  
  Zuul:
    container_name: Zuul
    image: "zuul"
    build: ./Zuul-Gateway
    ports:
      - "8762:8762"
    hostname: Zuul
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://serviceregistry:8761/eureka/
    depends_on:
      - "Eureka"